### ISSUE TITLE
Random song on space

### ISSUE THREAD

**Issue by PhilipTrauner** [mjarlund/MusicBee-QuickPlay-Overlay#1]
First up: Great plugin! I gave been searching for something that can replicate the macOS music playback experience on Windows for a while and this definitely is a big step towards that goal.

The only problem I am experiencing (on 1.0.3) is that the panel closes as soon as I hit space bar and a random track starts playing. I am using Alt+Space as a shortcut, just as hinted at in the README.

![2017-01-01_17-07-29](https://cloud.githubusercontent.com/assets/9287847/21581910/02e9e2a6-d045-11e6-86fa-82bf8c391868.gif)

**Comment by mjarlund** [comment]
Hi Phillip, sorry about the late response, have been busy and your response was lost in the pile of things to do. First off, I'm glad you like my plugin! I don't seem to be able to replicate the error, have you downloaded the latest release of the plugin? Let me know if the problem persists, I'll be more than happy to help fix the bug!

**Comment by PhilipTrauner** [comment]
Figured out the issue after some more trial-and-error. I had Spacebar set as my start playback key in MusicBee `(╯°□°）╯︵ ┻━┻`. Sorry for bothering you.

**Comment by mjarlund** [comment]
Haha, it happens, don't worry about it! I'm just happy to see people actually using my plugin, as this is the first piece of software I've ever released to the public. I'm going to release an update soon that will allow you to search by artist and album as well :-)

**Comment by PhilipTrauner** [comment]
Great, looking forward to it! 👍

**Comment by Minibrams** [comment]
> Haha, it happens, don't worry about it! I'm just happy to see people actually using my plugin, as this is the first piece of software I've ever released to the public. I'm going to release an update soon that will allow you to search by artist and album as well :-)

Any chance this can be reopened.

**Comment by bruunand** [comment]
> Any chance this can be reopened.

At the very least, some acknowledgment or reasoning for keeping this closed should be provided. Silence undermines the trust and goodwill that open source depends on.
